USE  OFFICE;
CREATE TABLE WORKER (WORKER_ID INT,FIRST_NAME CHAR(25),LAST_NAME CHAR(25),SALARY INT(15),JOINING_DATE datetime,DEPARTMENT CHAR(25));
INSERT INTO WORKER VALUES(1,'RAJ','TIKAN',45000,'2023-01-15 09:30:00','IT');
INSERT INTO WORKER VALUES(2,'RAMEESA','TAKKON',32000,'2021-05-10 09:00:00','HR'),(3,'NITA','JATA',34300,'2022-09-20 09:00:00','FINANCE'),
(4,'RAJ','KUMAR',50000,'2019-04-22 09:00:00','IT'),(5,'RAMESH','KUMAR',39000,'2023-06-10 09:00:00','HR');
SELECT * FROM WORKER;
DELIMITER $$
CREATE PROCEDURE  NEW_DATA(P_W_ID INT,P_F_NAME CHAR(25),P_L_NAME CHAR(25),P_SALARY INT(15),P_JOINING_DATE DATETIME,P_DEPARTMENT CHAR(25))
BEGIN
INSERT INTO WORKER(WORKER_ID ,FIRST_NAME ,LAST_NAME ,SALARY ,JOINING_DATE ,DEPARTMENT )
 VALUES (P_W_ID ,P_F_NAME ,P_L_NAME,P_SALARY ,P_JOINING_DATE ,P_DEPARTMENT);
 END $$
 DELIMITER ;
 
CALL NEW_DATA(6,'NITI','UMAR',35900,'2023-04-05 09:30:00','HR');
SELECT * FROM WORKER;


DELIMITER $$
CREATE PROCEDURE  SALARY_OF_WORKERS(IN P_W_ID INT,OUT P_SALARY INT(15))
BEGIN
SELECT SALARY INTO P_SALARY FROM WORKER WHERE WORKER_ID=P_W_ID;
 END $$
 DELIMITER ;
 
CALL SALARY_OF_WORKERS(2,@SALARY);
SELECT @SALARY AS SALARY;

DELIMITER $$
CREATE PROCEDURE  UPDATE_DEPARTMENTS(IN P_W_ID INT,IN P_DEPARTMENT CHAR(25))
BEGIN
UPDATE WORKER SET DEPARTMENT=P_DEPARTMENT WHERE WORKER_ID=P_W_ID;
 END $$
 DELIMITER ;
 CALL UPDATE_DEPARTMENTS(1,'SALES');
 
 DELIMITER $$
CREATE PROCEDURE  COUNT_WORKERS(IN P_DEPARTMENT CHAR(25),OUT P_WORKER_COUNT INT)
BEGIN
SELECT COUNT(*) INTO P_WORKER_COUNT FROM WORKER WHERE DEPARTMENT=P_DEPARTMENT;
 END $$
 DELIMITER ;
 CALL COUNT_WORKERS('HR',@COUNT_);
 select @COUNT_ AS NO_OF_WORKERS_IN_HR;
 
  DELIMITER $$
CREATE PROCEDURE  AVG_SALARY_DEPARTMENT(IN P_DEPARTMENT CHAR(25),OUT P_AVG_SALARY INT(15))
BEGIN
SELECT avg(SALARY) INTO P_AVG_SALARY FROM WORKER WHERE DEPARTMENT=P_DEPARTMENT;
 END $$
 DELIMITER ;
 CALL AVG_SALARY_DEPARTMENT('HR',@AVG_);
 select @AVG_ AS AVG_SALARY;
 

 
