use school;
create table  teacher (id int,name char(25),subject char(25),experience int,salary int(7));
insert into teacher values(1,'RAJI','MATHS',4,35000),(2,'NIRMAL','MALAYALAM',2,28000),(3,'BINU','BIOLOGY',6,38000),
(4,'RAJITHA','ZOOLOGY',3,36000),(5,'LAYA','IT',2,25000),(6,'BINLAL','ENGLISH',5,35000),(7,'JINU','MALAYALAM',3,32000),
(8,'LIJAR','MATHS',8,39000);
SELECT * FROM TEACHER;
DELIMITER $$
CREATE TRIGGER BEFORE_INSERTTEACHER
BEFORE INSERT ON TEACHER
FOR EACH ROW
BEGIN
IF NEW.SALARY<0 THEN 
SIGNAL sqlstate '45000'
SET MESSAGE_TEXT ='SALARY CANNOT BE NEGATIVE';
END IF;
END $$
DELIMITER ;
INSERT INTO TEACHER VALUES(8,'RAJIna','MATHS',4,-4567);
CREATE TABLE TEACHERS_LOG (LOG_ID INT PRIMARY KEY auto_increment, TEACHER_ID INT,ACTION_TYPE VARCHAR(20),ACTION_TIME TIMESTAMP);
DESC TEACHERS_LOG;
DELIMITER $$
CREATE TRIGGER AFTER_INSERTTEACHERS
AFTER INSERT ON TEACHER
FOR EACH ROW
BEGIN
INSERT INTO TEACHERS_LOG(TEACHER_ID,ACTION_TYPE,ACTION_TIME)VALUES(NEW.ID,'IN',NOW());
END $$
DELIMITER ;
INSERT INTO TEACHER VALUES(8,'RAJIna','MATHS',4,4567);
select * from TEACHERS_LOG;
DELIMITER $$
CREATE TRIGGER BEFORE_DELETETEACHERS
BEFORE DELETE ON TEACHER
FOR EACH ROW
BEGIN
IF OLD.EXPERIENCE>7 THEN 
SIGNAL sqlstate '45000'
SET MESSAGE_TEXT ='CANNOT DELETE';
END IF;
END $$
DELIMITER 
DELETE FROM TEACHER WHERE ID=8;
DELIMITER $$
CREATE TRIGGER AFTER_DELETETEACHERS_
AFTER DELETE ON TEACHER
FOR EACH ROW
BEGIN
INSERT INTO TEACHERS_LOG(TEACHER_ID,ACTION_TYPE,ACTION_TIME)VALUES(OLD.ID,'DELETE',NOW());
END $$
DELIMITER 
DELETE FROM TEACHER WHERE ID=7;
SELECT *from TEACHER_LOG;

